### ISSUE TITLE
Create monthly email to celebrate wins more publicly

### ISSUE THREAD

**Issue by evandinsmore** [Shopify/to-productdesign#10]
## Problem
We don't celebrate enough wins between launches.

## Why
Celebrating small wins increases team morale, particularly on projects with long timelines.

## Success Metrics
- We have a monthly email sent out to celebrate wins. This could be sent to Product Design only, or include UX or R&D, scope tbd.

## Team/Stakeholders
Product Design Team

## Implementation Plan
- [ ] Get input from Product Design Team whether this project will be useful, and the scope of the email
- [ ] Create a reminder bot in slack to collect wins at the end of each month
- [ ] Compile wins into an email and send to the team at the end of each month

**Comment by tranhelen** [comment]
Great implementation plan 👍 
Question: Step #4, when you say send to team, who would you like this email sent to?

Are you expecting to do this all Ev?
