### ISSUE TITLE
Bring back local events doc

### ISSUE THREAD

**Issue by MarielVandeloo** [Shopify/to-productdesign#15]
## Problem
We're not currently aware of local events / activities, and so we're not participating as much as we could be in local events.

## Why
To be active in the community, to be known "thought leaders" and for recruiting opportunities.

## Success Metrics
The team is attending more events!

## Team
@tranhelen 

## Stakeholders
Design Leads, Product Design Team

## Implementation Plan
- [ ] Bring back the Local Events doc
- [ ] Share with team
- [ ] Find a way to make sure that it doesn't disappear
