### ISSUE TITLE
Hack Days, Female Candidates - Follow-up

### ISSUE THREAD

**Issue by tranhelen** [Shopify/to-productdesign#17]
## Problem
There are 68 candidates that need to have first contact.

## Why
Sophia won't have time.

## Success Metrics
All candidates in Lever have moved either to Initial Vetting 

## Team
Helen + Design Leadership

## Stakeholders
Design Leadership + Sophia

## Implementation Plan
- [ ] Send out first reach-outs to anyone who is either a Designer or Product Designer
- [ ] Contact James Wood about the Illustrations
- [ ] @darrinhenein to go through the Industrial Design applicants
