### ISSUE TITLE
How To Run Design Exercises

### ISSUE THREAD

**Issue by anthonymenecola** [Shopify/to-productdesign#19]
## Problem
Many of the designers on our team have never facilitated a design sprint or design exercise with their team. 

## Why
By doing practice runs of these exercises we can begin to feel more comfortable running an exercise with a larger audience or facilitating a design sprint.

## Success Metrics
Designers opt-in to participate in specific workshops they want to learn more about.

## Team
Anyone who has run a sprint or a design exercise before can share their learnings with others.

## Implementation Plan
- [ ] Anthony to put together Service Blueprint workshop
- [ ] Andrey to put together Design Sprint workshop
- [ ] Assemble Workshop signup spreadsheet
- [ ] Run a workshop

**Comment by ilialarionov** [comment]
There was a learning session on how to run/create workshops, for some reason im having trouble finding a link to it.
