### ISSUE TITLE
More RnD and Lightning talks from designers

### ISSUE THREAD

**Issue by andreygargul** [Shopify/to-productdesign#20]
## Problem
Being more vocal about our job.

## Why
It will help us to scaling design influence across the organization and make everyone advocate for users.

## Success Metrics
Every time we do Lightning talks from Toronto we have a designer presenting
Every second time we do RnD talks from Toronto we have a designer presenting

## Team
Andrey

## Implementation Plan
- [ ] Find out RnD Lightning talk schedules
- [ ] Create help docs 
- [ ] Find who can help with coaching for that
