### ISSUE TITLE
Time management for creatives

### ISSUE THREAD

**Issue by vazquez** [Shopify/to-productdesign#23]
## Problem
Designers need to know what their 100% capacity is, so that we can more accurately know our limits.

## Why
In order to prepare for an 80/20 energy split (where we are spending 20% of our time in personal growth areas), we need to learn how to manage more time more effectively so that we are doing our best work.

Related issue: https://github.com/Shopify/to-productdesign/issues/8

## Success Metrics
We know the capacity levels of all members in product design, and we feel energized by the 20% time we are given to become better designers.

## Team/Stakeholders
- Darrin / Helen / Ilia
- Mariel / Ricardo / Dave W

## Implementation Plan
- [ ] Research time management for creatives
- [ ] Hire expert/take course on time management for creatives
- [ ] Survey designers to find out time-sinks/ high energy tasks
