### ISSUE TITLE
Compile list of idle projects/ideas that could use design resources

### ISSUE THREAD

**Issue by evandinsmore** [Shopify/to-productdesign#24]
## Problem
Projects with long timelines or lacking development resources can stall and a product designer's impact may go down as a result, potentially causing burnout or lowered morale.

## Why
Having a list of idle projects would give product designers who need a temporary break from longer projects, or who have spare time and feel like they're not having enough impact, an opportunity to work on something new and different, thus increasing morale and impact.

## Success Metrics
- We have a list of idle projects/ideas that need design resources
- More idle projects start getting completed

## Team/Stakeholders
- Product Design Team
- Product Managers
- BizDev?

## Implementation Plan
- [ ] Ask PMs and design leads if they would be on board with the idea of an idle project list
- [ ] Create a list in Google Sheets with input from PMs and design leads. This should include relevant information such as the design requirements, deadlines, team, slack channels, etc.
- [ ] Make product designers aware of the project list, possibly a round table talk?
- [ ] Bug PMs/BizDev/leads to periodically update priorities and to add new projects
