### ISSUE TITLE
Teach each other through workshops

### ISSUE THREAD

**Issue by vazquez** [Shopify/to-productdesign#26]
## Problem
We have a wealth of talent and skills available in the Product Design team, but we're not good at teaching each other to level up our collective skills.

## Why
Learning from each other not only leads to a more cohesive/unified team, but it also brings a more direct level of learning to the entire team.

## Success Metrics
- We will be constantly learning and teaching each other.

## Team
@vazquez
@MarielVandeloo 
Dave W

## Stakeholders
The entire product design team.

## Implementation Plan
- [ ] Create workshop sign-up sheet
- [ ] Make everyone take the Workshop workshop
- [ ] Mentor people in creating teaching material
