### ISSUE TITLE
Quarterly products roadmap update from higher management

### ISSUE THREAD

**Issue by andreygargul** [Shopify/to-productdesign#27]
## Problem
Sometimes, teams feel that there is a misalignment on product vision between them and higher management.

## Why
Creates confusing, damages team morale

## Success Metrics
Better aligned as an organization

## Implementation Plan
- [ ] Talk to leads
- [ ] Who should represent this "higher management" level
- [ ] Pitch the idea
