### ISSUE TITLE
Explain design work value in unicorn projects

### ISSUE THREAD

**Issue by bytino** [Shopify/to-productdesign#28]
## Problem
Represent UX across the company and be vocal about our work

## Why
Make it easier for the team you're working with to stay up to date with the progress you're making

## Success Metrics
The team is always up to date
Avoid issues related to design work during health checks

## Implementation Plan
- [ ] Update your unicorn project on a weekly basis
- [ ] Link prototypes and/or InVision projects
- [ ] Link research results

**Comment by ilialarionov** [comment]
hey, trying to understand the project title and the problem description. Is the problem the lack of value placed on UX work within projects? or is this UX within Shopify in general? What is the actual problem statement?

**Comment by bytino** [comment]
I think the problem is that there's not enough focus on UX work in unicorn projects. For the POS redesign for example, the designers add UX updates to the project every week to communicate their progress and problems they're trying to solve. It helps a lot to keep the team aligned and in the loop. You usually don't see that kind of detail on other projects.
