### ISSUE TITLE
Improve communication between designers and PMs

### ISSUE THREAD

**Issue by supervee** [Shopify/to-productdesign#30]
## Problem
We need to improve the relationship between PMs & Designers by creating stronger alignment of long term goals and consistently evaluate these goals together.

## Why
It will help decrease the confusion around expectations and foster better communication. Better communication between team members can help decrease burn out, provide better alignment and benefit the project team's progress overall. 

## Success Metrics
- Are 1:1's happening?
- Are people finding the 1:1s useful?
- Are designers feeling more confident about their relationship with their PMs?

## Team
- Product Design Team
- Product Managers

## Stakeholders
- Product Design Team

## Implementation Plan
- [ ] Create a framework to help facilitate 1:1s between PMs & Designers. Work with someone from the PM team to make sure they are aware of the problem and on board with the framework
- [ ] Add to product design onboarding
- [ ] Round table talk about facilitating alignment within your team
- [ ] Start having 1:1s !
- [ ] Send out a follow up survey to figure out the effectiveness of the framework and the 1:1s themselves

**Comment by ilialarionov** [comment]
Hey, could you list out or outline the problems between designers and PMs right now. i think you are touching on some of them under the "Why"

**Comment by supervee** [comment]
@ilialarionov added a bit more to the Problem section
