### ISSUE TITLE
Define and document new Freedom Friday format

### ISSUE THREAD

**Issue by lukesartori** [Shopify/to-productdesign#32]
## Problem

The current format for Freedom Friday is not working the best it could with low participation and completion.

## Why

Everyone agrees FF is a great initiative for personal development but find it difficult to maintain a regular cadence and have accountability to participate. Revising the current format will hopefully address these issues.

## Success Metrics
- Every designer completes (at least one) self directed personal development project before the end of the year.
- Everyone in the TO product design team knows what each other is working on.

## Team

TO Product design team

## Stakeholders
- @tranhelen @ilialarionov @darrinhenein 

## Implementation Plan
- [ ] Define new format
- [ ] Document new format in the Vault
- [ ] Review new format with leads and team
- [ ] Revise format if needed

**Comment by ilialarionov** [comment]
do we know whats not working in the current format?
