### ISSUE TITLE
Everyone has a Freedom Fridays project

### ISSUE THREAD

**Issue by vazquez** [Shopify/to-productdesign#33]
## Problem
We don't team up to learn challenging things during our personal development time.

## Why
No structure set in place that allows for teams of people to learn together.

## Success Metrics
- Every designer holds themselves accountable to their team
- A designer can choose to pair learn with someone that shares the same learning goals.

## Team
TO Product Design team

## Stakeholders
@tranhelen @ilialarionov @darrinhenein

## Implementation Plan
- [ ] Designers can pair in groups up to 3
- [ ] There needs to be a centralized place where designers can browse, and enter interests
- [ ] Project list will be pinned to slack channel
- [ ] Define Github project template (issue template)

**Comment by ilialarionov** [comment]
what are some of the benefits to group learning or teaming up? Could be worth outlining it in the problem statement.

**Comment by tranhelen** [comment]
> A designer can choose to pair learn with someone that shares the same learning goals.
Not a success metric :) Be careful what you're using to gauge success.

**Comment by tranhelen** [comment]
> A designer can choose to pair learn with someone that shares the same learning goals.
Not a success metric :) Be careful what you're using to gauge success.
