### ISSUE TITLE
Designers complete their Freedom Friday Project

### ISSUE THREAD

**Issue by aaronlegaspi** [Shopify/to-productdesign#34]
## Problem
Freedom Friday Projects lack incentive to for completion.

## Why
Completion is proof that the designer has met their goal stated at the beginning of the project.
Complete is a signal that the designer has acquired some degree of knowledge or skill.

## Success Metrics
- Designer provides tangible deliverable for all Geekbot updates
- Designer has demonstrated that they have hit all milestones
- Designer has presented completed project during round table

## Team
TO Product Design Team

## Implementation Plan
- [ ] Define medium for recording and tracking project completion.
- [ ] Send out survey asking about which incentives work best as prizes for completion.
- [ ] Define prize to award designers for completion
- [ ] Define method for celebrating completion of project

**Comment by tranhelen** [comment]
I challenge 'incentives' here. You cannot motivate someone extrinsically. You should want to better yourself and if you don't–it really is your loss in the end.
