### ISSUE TITLE
Freedom Friday updates and show & tell schedule

### ISSUE THREAD

**Issue by lukesartori** [Shopify/to-productdesign#35]
## Problem
We don't have a consistent and structured way to share our Freedom Friday progress with the rest of the team. 

## Why
Sharing your progress weekly/monthly with the team will help designers to be accountable for their own self directed learning project. It will also surface domain knowledge within the team 

## Success Metrics
- All designers share a progress update once a week on friday mornings, possibly via a slackbot, similar to our standup updates.
- All designers will be encouraged to share their progress at roundtable show and tell each month - Lighting talk style (max 2mins)

## Team
All TO product designers

## Stakeholders

@tranhelen @ilialarionov @darrinhenein 

## Implementation Plan
- [ ] Create monthly roundtable show and tell presentation schedule
- [ ] Share schedule with team and revise and conflicts
- [ ] Set up slackbot for weekly updates

**Comment by ilialarionov** [comment]
is the idea to have a new slackbot for updates or roll this up into the current geekbot?
