### ISSUE TITLE
Print your work and put it on walls

### ISSUE THREAD

**Issue by bytino** [Shopify/to-productdesign#7]
## Problem
Represent UX across the company and be vocal about our work

## Implementation Plan
- [ ] Print the work you want feedback on and bring it to Fresh Eyes
- [ ] Put it on a wall in your POD
- [ ] Get feedback on your work

**Comment by tranhelen** [comment]
Feedback
- How would you communicate this to the rest of the Design team?
- The implementation plan should be written in the perspective of, "If we were going to run the initiative as an owner, how would we make sure this happens" not necessarily from the POV of the Designer themselves
