### ISSUE TITLE
Get the team to 80% capacity

### ISSUE THREAD

**Issue by tranhelen** [Shopify/to-productdesign#8]
## Problem
Team needs more time and are likely all over-capacity.

## Why
If we do not do this the team will feel too stressed to work on their own growth and won't have team to work on Design Team initiatives.

## Success Metrics
Everyone 

## Team/Stakeholders
Darrin / Ilia / Helen

## Implementation Plan
- [ ] Create a survey to ask people where they are now
- [ ] Figure out what the count is across the team
- [ ] Understand what number to hire for
- [ ] Adjust resourcing doc
